spring:
  datasource:
    url: jdbc:mysql://172.16.200.42:3306/testdb?characterEncoding=utf-8&amp;allowMultiQueries=true&amp;zeroDateTimeBehavior=convertToNull
    username: dev_w
    password: devw@234